version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: docker-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - "./data/redis:/data"
      - "./data/redis.conf:/usr/local/etc/redis/redis.conf"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    sysctls:
      net.core.somaxconn: '511'
    labels:
      - "Docker Redis"
    restart: unless-stopped

  app:
    build: .
    container_name: counter
    volumes:
      - "./data/app:/usr/local/openresty/nginx/conf/app"
      - "./data/logs:/usr/local/openresty/nginx/logs"
    depends_on:
      - redis
    ports:
      - "8001:80"
    links:
      - redis:redis.local
