version: '3'
services:
  redis:
    image: "redis:alpine"
    expose:
      - 6379

  resty_counter:
    build: .
    volumes:
      - "./tmp/conf:/usr/local/openresty/nginx/conf/conf.d"
      - "./tmp/logs:/usr/local/openresty/nginx/logs"
    depends_on:
      - redis
    ports:
      - "8001:80"
    links:
      - redis:redis.local
